### PR TITLE
Addfaqandvideos

### PR DESCRIPTION
**Pull request by jukent**
I've embedded the youtube videos into the site, added the new FAQ, and adjusted some formatting between the FAQS for consistency.

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
Looks great.  Thanks, @jukent!

**Comment by jukent** [comment]
@kmpaul The videos appeared when building locally, but now they seem to have just left white space on the page where the embedded video should be on the site.

**Comment by kmpaul** [comment]
That's unfortunate. Hmm. Is it a permissions thing?  Like, we can watch videos from YouTube on our browser because we are logged in to Google. But maybe the settings on the videos limit who can watch?

**Comment by jukent** [comment]
The visibility settings are set to "Public".

This seems to be a not uncommon issue with `iframe` -- https://stackoverflow.com/questions/19129615/iframe-to-load-video-works-fine-locally-but-not-working-in-server

**Comment by kmpaul** [comment]
Good find. Looks like you need to use a video tag inside the iframe.

**Comment by jukent** [comment]
> Good find. Looks like you need to use a video tag inside the iframe.

I had tried that and it stopped building locally as well. I think the raw html blocks is the way to go.

**Comment by jukent** [comment]
This was fixed by #71

**Pull request merged**
